USE [Escola]
GO

/****** Object:  Table [dbo].[Login]    Script Date: 15/12/2023 21:39:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Login](
	[ID_LOGIN] [int] IDENTITY(1,1) NOT NULL,
	[USUARIO_LOGIN] [varchar](150) NOT NULL,
	[SENHA_LOGIN] [varchar](150) NOT NULL,
	[NIVEL_LOGIN] [varchar](80) NOT NULL,
	[EMAIL_LOGIN] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_LOGIN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

