USE [Escola]
GO

/****** Object:  Table [dbo].[Cadastro_Aluno]    Script Date: 11/12/2023 16:13:08 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Cadastro_Aluno](
	[ID_ALUNO] [int] IDENTITY(1,1) NOT NULL,
	[NOME_ALUNO] [varchar](130) NOT NULL,
	[TELEFONE_ALUNO] [varchar](15) NOT NULL,
	[GENERO_ALUNO] [varchar](50) NOT NULL,
	[NASCIMENTO_ALUNO] [datetime] NOT NULL,
	[ENDERECO_ALUNO] [varchar](50) NOT NULL,
	[BAIRRO_ALUNO] [varchar](50) NOT NULL,
	[CEP_ALUNO] [varchar](20) NOT NULL,
	[OBSERVACOES_ALUNO] [varchar](200) NULL,
	[RG_ALUNO] [varchar](30) NOT NULL,
	[CPF_ALUNO] [varchar](30) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_ALUNO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

